# Generated by Django 3.1.13 on 2021-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0040_cloud_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='certificate_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='order_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
