# Generated by Django 3.1.13 on 2021-10-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0041_auto_20211021_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='certificate_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
