# Generated by Django 3.1.13 on 2021-10-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0042_auto_20211021_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
