# Generated by Django 3.1.13 on 2021-12-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_auto_20211024_0949'),
        ('engine', '0044_auto_20211123_0824'),
    ]

    operations = [
    ]
