# Generated by Django 3.1.13 on 2021-12-02 14:22

import cvat.apps.engine.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0044_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='hash',
            field=cvat.apps.engine.models.SafeCharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
