# Generated by Django 3.1.13 on 2021-12-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0045_activitylog_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='type',
            new_name='activity_type',
        ),
    ]
