# Generated by Django 3.1.13 on 2021-12-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0046_auto_20211202_1424'),
        ('engine', '0045_merge_20211205_1537'),
    ]

    operations = [
    ]
