FROM openvino/cvat_server

RUN apt-get update && apt-get -y install cron
RUN python3 -m pip install --no-cache-dir requests_toolbelt

# Copy cronjob to 
COPY cronjob.py ${HOME}/

# Copy cron file to the cron.d directory
COPY cron /etc/cron.d/cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cron

# Apply cron job
RUN crontab /etc/cron.d/cron
 
# Run the command on container startup
CMD cron