version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from /s3-bucket host directory'
    volumes:
      - /s3-bucket:/home/django/share:ro

#volumes:
#  cvat_share:
#    driver_opts:
#      type: none
#      device: /s3-share
#      o: bind
